### ISSUE TITLE
直接崩溃

### ISSUE THREAD

**Issue by yanchunlan** [drawthink/ExpandableRecyclerView#2]
clone了一份代码，直接调 gradle 4.0 ,plugin 3.0 , 其余配置调到最新，一运行，直接崩溃

**Comment by ehuashao** [comment]
有错误信息么。

**Comment by aaaddduuu** [comment]
在TextFragment类中，注释掉第45行Integer.valueOf("as");然后再运行就ok了

**Comment by drawthink** [comment]
demo中bug解决了。
