### ISSUE TITLE
你好，发现一个bug

### ISSUE THREAD

**Issue by KDL-in** [drawthink/ExpandableRecyclerView#4]
不同分组之间，如果子项用的都是String类型且子项有相同的字符串就会出问题。
比如这组数据
    private static String[] groupNames = {"ITEM1",  "ITEM2","ITEM3"};
    private static String[][] childNames = {
            {"List 1", "List 2", "List 3", "List 4","List 5"},
            {"C 1", "C 2"},
            {"List 1", "List 2", "List 3"},
    };
定义是extends BaseRecyclerViewAdapter<String, String, VHTaskListRecyclerView>
====================================
我猜测是这样的，String的hashCode函数生成方式是一样的，导致出现相同的hashCode，验证
1. 把数据改成相互不同的
2. 将String封装为对象<Group,Child,VHTaskListRecyclerView>
以上两种都可以正常运行。但是我觉得潜在问题还是挺大的

**Comment by KDL-in** [comment]
怎么样能支持adapter.notifyItemRemoved()方法

**Comment by drawthink** [comment]
多谢提醒，现在已经转Java开发了，没时间维护了，有兴趣可以试着自己改一改啊。

**Comment by KDL-in** [comment]
@drawthink 现在比较急用，我需要在源代码上做些修改，我直接fork修改先用着先（个人使用），新手开发者，github不是很熟，如果哪里做得不妥当，请见谅
